[package]
name = "black_list"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.9"
serde_json = "1.0.134"
url = "2.5.4"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
csv = "1.3.1"
